apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::534859277684:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-M4YPHDDPJRRS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:main
      rolearn: arn:aws:iam::534859277684:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-31T09:02:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1668"
  uid: fd9f06e2-8600-4507-ba2b-52d894d3f83e
